# Generated by Django 3.2.6 on 2021-08-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjas',
            name='desc',
            field=models.CharField(default='dojo antiguo', max_length=255),
            preserve_default=False,
        ),
    ]
