# Generated by Django 3.2.6 on 2021-08-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_ninjas_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninjas',
            name='desc',
        ),
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.CharField(default='dojo antiguo', max_length=255),
            preserve_default=False,
        ),
    ]
